# Configura��es do Banco de Dados (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/security_db
spring.datasource.username=postgres
spring.datasource.password=Keven#123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configura��es do Pool de Conex�es (HikariCP)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

# Configura��es do JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configura��es da API (Security/JWT)
api.security.token.secret=8SjFSqSJ6DYAcBJrNGN76hEhcij5vtyJK5G819CvV7Fm32131ds